### ISSUE TITLE
what is the weird blank space over the dialog?

### ISSUE THREAD

**Issue by paxdron** [ashishbhandari/AndroidTabbedDialog#2]

**Comment by ashishbhandari** [comment]
could you attach screenshot or describe it more in which version you are facing this issue?

**Comment by paxdron** [comment]
The blank space over the title.
on jellybean and lollipop
![screenshot_2016-05-03-02-54-00](https://cloud.githubusercontent.com/assets/11153664/14977673/a3180f66-10db-11e6-81f1-b891f1af6fac.png)

**Comment by paxdron** [comment]
Also, is there a way to omit the loader when you swipe the dialog?
![screenshot_2016-05-03-03-12-17](https://cloud.githubusercontent.com/assets/11153664/14977838/34e0264e-10dd-11e6-845a-eb8d0db6067e.png)
